global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'tempo'
    static_configs:
    - targets: ['tempo:3100']

  - job_name: 'node-manager'
    static_configs:
    - targets: ['18.209.6.249:9100']

  - job_name: 'telegraph'
    static_configs:
    - targets: ['18.209.6.249:9191']

  - job_name: 'loki'
    static_configs:
    - targets: ['loki:3100']

  - job_name: 'boot-otel-tempo-provider1'
    metrics_path: /actuator/prometheus
    static_configs:
    - targets: ['boot-otel-tempo-provider1:8090']

  - job_name: 'boot-otel-tempo-api'
    metrics_path: /actuator/prometheus
    static_configs:
    - targets: ['boot-otel-tempo-api:8080']

  - job_name: 'volume_exporter'
    metrics_path: /metrics
    static_configs:
    - targets: ['volume_exporter:9888']
